def menu():
    print("-------------------------------")
    print("Escolha uma opção:")
    print(" 1. Exibir Grafo")
    print(" 2. Busca em Profundidade (DFS)")
    print(" 3. Busca em Largura (BFS)")
    print(" 4. Algoritmo de Dijkstra")
    print(" 5. Algoritmo de Bellman-Ford")
    print(" 6. Algoritmo de Johnson")
    print(" 7. Exibir Fluxo")
    print(" 8. Verificar fluxo viável")
    print(" 9. Algoritmo de Fluxo Máximo")
    print("10. Algoritmo de Corte Mínimo")
    print("11. Grafo de Aumento de Fluxo")
    print("12. Algoritmo de Ford-Fulkerson")
    print("13. Algoritmo de Dinitz")
    print(" 0. Sair")
    print("-------------------------------")